### ISSUE TITLE
JSON result

### ISSUE THREAD

**Issue by zdenektopic** [GraphQLSwift/GraphQL#1]
Hi,

I am having trouble converting returned Map object to JSON. There seems to be no method to simply convert the result to simple dictionary convertible to JSON or any other obvious way.
Or at least simple string valid as HTTP response body.

**Comment by paulofaria** [comment]
Hello! The `Map`object is like most JSON types are represented currently in Swiftland. To get a JSON string simply call `description`.

```swift
let result = try graphql(schema: StarWarsSchema, request: query)
print(result.description)
```

example output:

```json
{
    "data": {
        "hero": {
            "name": "R2-D2"
        }
    }
}
```

In debug mode it will pretty print the JSON string. In release mode it will print a minified version.
If this is not enough let me know what you need. 😊

**Comment by paulofaria** [comment]
Just so you know I released [Graphiti](https://github.com/GraphQLSwift/Graphiti). Which is a swiftier DSL to create your types/schemas.

**Comment by paulofaria** [comment]
More news! Just released [GraphQLResponder](https://github.com/Zewo/GraphQLResponder). It's a Zewo responder (kinda like a middleware) with GraphiQL support included. 😊

**Comment by paulofaria** [comment]
ping!

**Comment by zdenektopic** [comment]
For me it returns:
```
"{
    "data": {
        "hero": {
            "name": "R2-D2"
        }
    }
}"
```

In those `"` :(

**Comment by zdenektopic** [comment]
Graphiti looks good, I am currently starting a new project and deciding between Vapor and Zewo.

**Comment by johndpope** [comment]
@zdenektopic  - this might help https://github.com/utahiosmac/Marshal

**Comment by zdenektopic** [comment]
I think it should support it out-of-box. I dont need mapping to object, I just need to get simple dictionary.
