### ISSUE TITLE
Custom Schema Directives? 

### ISSUE THREAD

**Issue by ScottRobbins** [GraphQLSwift/GraphQL#120]
Does this library support putting custom directives into your schema? 

I _think_ the answer is no, but I wanted to make sure. 

There are some directives that come [standard](http://spec.graphql.org/June2018/#sec-Type-System.Directives) with most GraphQL implementations, like `skip`, `include` and `deprecated`. But there are also other custom ones for implementations like Apollo Federation that aren't part of the GraphQL spec, but you may want to use for the schema you are defining on your server.

**Comment by NeedleInAJayStack** [comment]
Yeah, it definitely supports putting custom directives into your schema. See [Directives](https://github.com/GraphQLSwift/GraphQL/blob/main/Sources/GraphQL/Type/Directives.swift) and the documentation on top of [Schema](https://github.com/GraphQLSwift/GraphQL/blob/main/Sources/GraphQL/Type/Schema.swift). Note that the existing directives are defined almost identically to the [JavaScript](https://github.com/graphql/graphql-js/blob/main/src/type/directives.ts#L100) reference implementation.

As for adding the custom directives used by Apollo Federation, you will probably need to add their definition and execution logic similar to how Apollo does in their [Federation repo](https://github.com/apollographql/federation/blob/6474916e4267cb203f56c5645bc1a20392a2c9d9/subgraph-js/src/directives.ts)
