### ISSUE TITLE
Disabling introspection e.g. in production

### ISSUE THREAD

**Issue by alexsteinerde** [GraphQLSwift/GraphQL#122]
Please correct me if I'm wrong. But as I understand correctly, introspection is currently always enabled and cannot be disabled.
If that's true I would like to create a PR for this.
But maybe I'm missing something.

**Comment by NeedleInAJayStack** [comment]
Yeah, the introspection query is always added to the schema via [this line](https://github.com/GraphQLSwift/GraphQL/blob/a3011344bef0374fb72f4ad57a85460564eb8f0e/Sources/GraphQL/Type/Schema.swift#L64).

It's probably worth noting though that the reference JavaScript implementation appears to [do the same thing](https://github.com/graphql/graphql-js/blob/831394413b7b2a0eddfe6e65029acf98d0b2ee87/src/type/schema.ts#L205), and doesn't appear to offer options to limit this. Introspection-disabling appears to typically be offered by packages on top that use validation rules: [apollo example](https://github.com/apollographql/apollo-server/blob/d7e9b97595b063f1e796ec4449850a16d19e8b18/packages/server/src/ApolloServer.ts#L76), [other example](https://github.com/helfer/graphql-disable-introspection#readme).

I suppose that's all to say that I think it'd make sense to take a validation approach to this, and improve the validation system if that is not currently possible.

**Comment by alexsteinerde** [comment]
Actually there are multiple places where schema and type types are used. Here I prototyped the disabling of introspection natively: https://github.com/GraphQLSwift/GraphQL/compare/main...alexsteinerde:GraphQL:disable-introspection

I'm new to GraphQL validations. But with examples and by looking at a JavaScript implementation (https://github.com/helfer/graphql-disable-introspection/blob/master/index.js) I would say the following validation function would work, right?
```swift
func disableIntrospectionValidation(context: ValidationContext) -> Visitor {
    return Visitor(enter: { node, _, _, _, _ in
        if let field = node as? Field, ["__schema", "__type"].contains(field.name.value) {
            context.report(error: .init(message: "GraphQL introspection is not allowed, but the query contained __schema or __type", nodes: [node]))
        }
        return .continue
    })
}
```

**Comment by alexsteinerde** [comment]
If that validation works, the change would need to be in Graphiti to pass optional validation functions into the execution.

**Comment by alexsteinerde** [comment]
I'll submit a proposal for a PR once I find the time.

**Comment by alexsteinerde** [comment]
I created a PR in Graphiti and will close this issue.
https://github.com/GraphQLSwift/Graphiti/pull/105
