### ISSUE TITLE
GraphQLError missing `extensions`

### ISSUE THREAD

**Issue by rexmas** [GraphQLSwift/GraphQL#127]
GraphQLError appears to be missing the `extensions` property which is useful when supplying bespoke application or server specific data in an error payload back to clients https://github.com/GraphQLSwift/GraphQL/blob/2.5.1/Sources/GraphQL/Error/GraphQLError.swift

as seen in the spec here https://spec.graphql.org/October2021/#sel-IAPHRPZBABABJk5d

**Comment by NeedleInAJayStack** [comment]
Closing after the merge of this MR: https://github.com/GraphQLSwift/GraphQL/pull/128

**Comment by rexmas** [comment]
Thank you
