### ISSUE TITLE
Question regarding the public API

### ISSUE THREAD

**Issue by williambailey** [GraphQLSwift/GraphQL#15]
I was wondering if you had any objection to exposing more to the outside world? For example most of the classes and structs in `Language` and `Type` could become `public` along with their `let` properties with hopefully little impact. 

The more I play with this project the more I find that I need to set things as `public` so that it's available for use outside.

**Comment by paulofaria** [comment]
Yeah. I think so, it makes sense. Even more because this is a canonical implementation. Feel free to send a PR.
