### ISSUE TITLE
Scalar ID error in introspection

### ISSUE THREAD

**Issue by ZirgVoice** [GraphQLSwift/GraphQL#157]
When executing an introspection request I get the error "Serialize expected type ID but got Map". I am using ID from the pioneer library

**Comment by NeedleInAJayStack** [comment]
Hi @ZirgVoice, what version of the GraphQL package are you using?

**Comment by ZirgVoice** [comment]
2.10.3 I use Graphiti

**Comment by NeedleInAJayStack** [comment]
The error is coming from [this](https://github.com/GraphQLSwift/Graphiti/blob/main/Sources/Graphiti/Scalar/Scalar.swift#L25) line in Graphiti, which suggests that the way the `ID` scalar has been hooked up has no `serialize` method. It's worth noting that Graphiti does not include ID in [the set of default scalars that are automatically registered in every schema](https://github.com/GraphQLSwift/Graphiti/blob/main/Sources/Graphiti/Schema/SchemaTypeProvider.swift#L11).

I'm not very familiar with Pioneer. Can you share the code that includes the `ID` scalar into your schema?

**Comment by ZirgVoice** [comment]
I use the asScalar function https://github.com/d-exclaimation/pioneer/blob/c412d3685ebd840a57404032b97ad8d1ca047653/Sources/Pioneer/GraphQL/BuiltinTypes.swift#L46C24-L46C32

**Comment by NeedleInAJayStack** [comment]
This seems to be a bug in Pioneer, in that it doesn't provide `serialize`, `parseValue`, or `parseLiteral` closures. My suggestion is that Pioneer use [`GraphQLID`](https://github.com/GraphQLSwift/GraphQL/blob/main/Sources/GraphQL/Type/Scalars.swift#L225) directly in its `asScalar` method like:

```swift
    public static func asScalar<Resolver, Context>() -> Scalar<Resolver, Context, Self> {
        .init(
            ID.self,
            as: "ID",
            serialize: { value, _ in
                try GraphQLID.serialize(value)
            },
            parseValue:  { inputValue, _ in
                try GraphQLID.parseValue(inputValue)
            },
            parseLiteral:  { ast, _ in
                try GraphQLID.parseLiteral(ast)
            }
        ).description("...")
    }
```

Alternatively, the `serialize` closure could be defined manually in whatever way you like to get a  valid `Map` representation of the type from the `Any` serialize input.

**Comment by ZirgVoice** [comment]
Thanks a lot, it helped
