### ISSUE TITLE
Unable to install via SPM

### ISSUE THREAD

**Issue by captainbarbosa** [GraphQLSwift/GraphQL#52]
Hi, I'm not able to install v0.11.0 of this package through SPM (guessing the package name from the `Package.swift` file from this repo) within a Vapor 3.0.0 application. Here's a sample of my Package.swift:

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "myApp",
    products: [
        .library(name: "myApp", targets: ["App"]),
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0"),
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.6.0"),
        .package(url: "https://github.com/GraphQLSwift/GraphQL.git", from: "0.11.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor", "SwiftProtobuf", "GraphQL"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

When I try to `swift package update` my computer goes into overdrive, and hits 99% CPU usage until a force quit the process. I've tried this multiple times with the same result. If I remove the GraphQL dependency, everything installs as expected.

**Comment by paulofaria** [comment]
I'm not sure this is an issue with GraphQL did you try reporting this bug to the SwiftPM team?

**Comment by captainbarbosa** [comment]
I did not, but I can go ahead and try this with the latest version of Xcode/SPM since there have been a few upgrades in the past few months. I'll reopen this if the issue persists.

**Comment by paulofaria** [comment]
Did you get to test it?

**Comment by captainbarbosa** [comment]
I did, it seems to be working now. I used the latest version of this library as well as Xcode 11. Thanks for checking in.
