### ISSUE TITLE
Preserve result order

### ISSUE THREAD

**Issue by jbttn** [GraphQLSwift/GraphQL#60]
[7.2.2 Serialized Map Ordering](https://spec.graphql.org/June2018/#sec-Serialized-Map-Ordering)

> Since the result of evaluating a selection set is ordered, the serialized Map of results should preserve this order by writing the map entries in the same order as those fields were requested as defined by query execution. Producing a serialized response where fields are represented in the same order in which they appear in the request improves human readability during debugging and enables more efficient parsing of responses if the order of properties can be anticipated.

> For example, if the request was **{ name, age }**, a GraphQL service responding in JSON should respond with **{ "name": "Mark", "age": 30 }** and should not respond with **{ "age": 30, "name": "Mark" }**.

**Comment by paulofaria** [comment]
Thank you @jbttn! I'll take a stab at it this week.

**Comment by NeedleInAJayStack** [comment]
This was resolved for Map and GraphQLResult in the linked merge request. However, when encoding with an ordinary `JSONEncoder`, order is not preserved due to the internals of `JSONEncoder`.

**Comment by NeedleInAJayStack** [comment]
This was actually fixed in https://github.com/GraphQLSwift/GraphQL/pull/94 by providing a `GraphQLJSONEncoder` that preserves result ordering.
