### ISSUE TITLE
False positive with no unused variable rule

### ISSUE THREAD

**Issue by jbttn** [GraphQLSwift/GraphQL#61]
Variables contained within objects are not detected by the "no unused variable" rule:

```
query Foo($a: String) {
  field(object: { a: $a })
}
```

> "Variable "$a" is never used in operation "Foo"."

**Comment by kumararvind** [comment]
Any update on this, I am also facing similar issue

**Comment by kumararvind** [comment]
Commented NoUnusedVariablesRule to fix nested variable issue

https://github.com/GraphQLSwift/GraphQL/pull/85

@paulofaria  please check and update if it work, I have verified it is working fine.
