### ISSUE TITLE
Async Resolving

### ISSUE THREAD

**Issue by lightsprint09** [GraphQLSwift/GraphQL#7]
Async resolving would be the corner stone to use Swift GraphQL as an aggregation layer. We would need to introduce some async task handling.

**Comment by lightsprint09** [comment]
https://github.com/GraphQLSwift/Graphiti/issues/6

**Comment by paulofaria** [comment]
@lightsprint09 yeah for async frameworks that's true. The reason it is not async yet is because I use it mainly with Zewo which provides non-blocking synchronous APIs through coroutines. But an async API is indeed in the plans. I just gotta find time to work on it.

**Comment by williambailey** [comment]
@lightsprint09 does #13 help at all? In theory you should be able to use an instance of the `ConcurrentDispatchFieldExecutionStrategy` as the `queryStrategy:` parameter to the `graphql` function to enable concurrent field resolution/execution. You will still have to ensure that your field resolution functions behave as if they are synchronous and only return once they have, for example, completed their http request but this does mean that we don't have to provide support for `[insert favourite concurrent swift package here]` directly and you are free to build your resolution functions as you see fit.

With the potential updates in #18 you will also be exposed to more of the internal data structures and have access to both the schema and the request AST. This could potentially help any aggregation layer to look at the incoming request to see what information it might potentially need and adjust its request(s) as required.

**Comment by paulofaria** [comment]
Implented by #41
