### ISSUE TITLE
Is this library single-threaded only?

### ISSUE THREAD

**Issue by NeedleInAJayStack** [GraphQLSwift/GraphQL#75]
It looks like all the tests in this package use `MultiThreadedEventLoopGroup(numberOfThreads: 1)`. However, if the number of threads is changed to > 1, then a number of the tests become unstable and will occasionally cause errors or deadlocks. The [Graphiti](https://github.com/GraphQLSwift/Graphiti) tests use `MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount)` and I'm finding the same instability there.

Specifically, I found that the following tests become unstable:

* FieldExecutionStrategyTests
	* testSerialFieldExecutionStrategyWithMultipleFields (deadlock)
	* testSerialFieldExecutionStrategyWithMultipleFieldErrors (deadlock)
	* testConcurrentDispatchFieldExecutionStrategyWithMultipleFields (NIO+Extensions.swift, ln 42: EXC_BAD_ACCESS)
	* testConcurrentDispatchFieldExecutionStrategyWithMultipleFieldErrors (deadlock) (NIO+Extensions.swift, ln 42: EXC_BAD_ACCESS)
* StarWarsIntrospectionTests
	* testIntrospectionDroidKindQuery (deadlock)
	* testIntrospectionCharacterKindQuery (deadlock)
* StarWarsQueryTests
	* testDuplicateFieldsQuery (deadlock)
	* testUseFragmentQuery (deadlock)
	* testCheckTypeOfLukeQuery (deadlock)
	* testFetchLukeAndLeiaAliasedQuery (deadlock)

Is it expected that the input EventLoopGroup should always only have one thread?

**Comment by paulofaria** [comment]
@NeedleInAJayStack hey, Jay. Yeah, the library was based on the canonical JS library, which due to its JS nature it is inherently single-threaded. I'll leave this issue open so this information is easily available for others as well. We definitely welcome contributions to make it work on multithreaded environments.

**Comment by NeedleInAJayStack** [comment]
Thanks Paulo, that's good to know. I won't expect any multithreaded optimization in that case.

In the meantime, I've put in a pull request that fixes the test issues when running with multiple threads: https://github.com/GraphQLSwift/GraphQL/pull/76

Thanks again!

**Comment by NeedleInAJayStack** [comment]
Just to follow up on this, I've been successfully running this on MultiThreadedEventLoops for quite some time now with no issues. I think we can safely say that this package is safe for multithreaded environments.
