### ISSUE TITLE
Is there a way to validate a document with custom validation rules?

### ISSUE THREAD

**Issue by d-exclaimation** [GraphQLSwift/GraphQL#98]
Hey, I am maintaining a GraphQL server library that uses this package. I am planning to allow the user of my library to add additional custom validation rules which will be used to validate incoming requests before they are executed. My library is heavily inspired by `apollo-server` and looking at their approach, they are using the `graphql-js` validate function [here](https://github.com/apollographql/apollo-server/blob/c35086a5277f87161b596b77f0c7ae48e6d76f45/packages/apollo-server-core/src/requestPipeline.ts#L245). 

I figured this package should also have the same function, but the only validate function that is public doesn't accept any custom rules.

https://github.com/GraphQLSwift/GraphQL/blob/283cc4de56b994a00b2724328221b7a1bc846ddc/Sources/GraphQL/Validation/Validate.swift#L11

I found out that the primary entry point function already perform validation but it also doesn't accept custom validation rules.

https://github.com/GraphQLSwift/GraphQL/blob/151c2f18dd12bd7bb6ab301a212c1da2010415ea/Sources/GraphQL/GraphQL.swift#L92

It seemed like this library already have the function and struct needed for custom validation, but they are just not public. I am not sure if this is a intentional decision.

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, before I mash merge on [this PR](https://github.com/GraphQLSwift/GraphQL/pull/99), was scoping the validation functions as `internal` an intentional decision?

**Comment by paulofaria** [comment]
@NeedleInAJayStack not that I can't remember. Probably out of habit.
